[project]
name = "internship"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "beautifulsoup4>=4.15.0",
    "grandalf>=0.8",
    "ipykernel>=7.2.0",
    "keras>=3.14.1",
    "langchain",
    "langchain-classic>=1.0.8",
    "langchain-community>=0.4.2",
    "langchain-experimental>=0.4.2",
    "langchain-google-genai>=4.3.3",
    "langchain-text-splitters>=1.1.2",
    "matplotlib>=3.10.9",
    "numpy>=2.4.6",
    "pandas>=3.0.3",
    "pypdf>=6.17.0",
    "scikit-learn>=1.9.0",
    "seaborn>=0.13.2",
    "tensorflow>=2.21.0",
    "torchvision>=0.27.0",
    "tqdm>=4.70.0",
]

[tool.uv.workspace]
members = [
    "langchain",
]

[tool.uv.sources]
langchain = { workspace = true }
