[project]
name = "langchain"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "click>=8.4.2",
    "hf>=1.27.0",
    "langchain-google-genai>=4.3.3",
    "pydantic[email]>=2.13.4",
    "python-dotenv>=1.2.3",
    "streamlit>=1.61.1",
    "tqdm>=4.70.0",
    "transformers>=5.15.0",
]
